export type Product = {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  compareAt?: number;
  rating: number;
  sold: number;
  image: string;
  badge?: string;
  availability: 'In Stock' | 'Check bulk availability';
  bulk?: boolean;
  moq?: number;
  variants?: { name: string; values: string[] }[];
  specs: string[];
  description: string;
  reviews: string[];
  kitItems?: string[];
};


export const categories = [
  'Writing Supplies',
  'Paper Products',
  'Notebooks & Pads',
  'Art Supplies',
  'Office & Teacher Supplies',
  'Adhesives & Tapes',
  'Bags & Storage',
  'Calculators & Tech',
  'School Kits',
  'Deals',
];

const reviews = [
  'Good quality for daily school use. Sulit for the price.',
  'Ordered for class supplies and the pack size is practical.',
  'Looks neat and works well for students and teachers.',
];

export const products: Product[] = [
  { id:'mongol-pencil-12', name:'Mongol No. 2 Pencil 12-Piece School Pack', brand:'Mongol', category:'Writing Supplies', price:98, compareAt:120, rating:4.8, sold:4200, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/3633_210.jpg', badge:'18% OFF', availability:'In Stock', variants:[{name:'Pack',values:['12 pcs','24 pcs']}], specs:['No. 2 graphite pencils','Hexagonal barrel','Eraser tip','12 pieces per pack'], description:'Classic Mongol pencils for exams, writing drills, and daily classroom work.', reviews },
  { id:'faber-castell-pencil-12', name:'Faber-Castell Grip 2001 Pencil Set 12s', brand:'Faber-Castell', category:'Writing Supplies', price:179, compareAt:215, rating:4.7, sold:980, image:'https://down-id.img.susercontent.com/file/63e559d82ef43f4d0998b090808074d1', badge:'17% OFF', availability:'In Stock', variants:[{name:'Pack',values:['12 pcs','24 pcs']}], specs:['HB graphite','Triangular grip style','Break-resistant lead','School writing set'], description:'Comfortable writing pencils for students who write for long study sessions.', reviews },
  { id:'pilot-gtec-c4', name:'Pilot G-Tec-C4 0.4mm Gel Pen', brand:'Pilot', category:'Writing Supplies', price:89, compareAt:99, rating:4.9, sold:2600, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/4053_129.jpg', badge:'10% OFF', availability:'In Stock', variants:[{name:'Ink Color',values:['Black','Blue','Red']}], specs:['0.4mm ultra fine tip','Gel ink','Needle point','Ideal for neat notes'], description:'Fine-tip gel pen popular for clean school notes, journaling, and exams.', reviews },
  { id:'pilot-acroball', name:'Pilot Acroball Ballpen 0.7mm', brand:'Pilot', category:'Writing Supplies', price:65, compareAt:75, rating:4.7, sold:1500, image:'https://down-ph.img.susercontent.com/file/sg-11134207-824g4-mfpi89c8dp1l6f', badge:'13% OFF', availability:'In Stock', variants:[{name:'Ink Color',values:['Black','Blue','Red']}], specs:['0.7mm ballpoint','Smooth low-viscosity ink','Comfort grip','Retractable'], description:'Smooth everyday ballpen for students, teachers, and office use.', reviews },
  { id:'panda-ballpen-box', name:'Panda Ballpen Blue 50-Piece Box', brand:'Panda', category:'Writing Supplies', price:295, compareAt:350, rating:4.6, sold:880, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/3887_1632.jpg', badge:'16% OFF', availability:'Check bulk availability', bulk:true, moq:5, variants:[{name:'Ink Color',values:['Blue','Black']}], specs:['50 pens per box','Ballpoint ink','Classroom and office pack','Bulk-friendly'], description:'Affordable bulk pen box for schools, classrooms, offices, and sari-sari resale.', reviews },
  { id:'hbw-matrix-pen-box', name:'HBW Matrix Ballpen 50-Piece Box', brand:'HBW', category:'Writing Supplies', price:285, compareAt:330, rating:4.6, sold:1200, image:'https://down-ph.img.susercontent.com/file/b82cedac0bc0d0674517ff4441b7434a', badge:'14% OFF', availability:'Check bulk availability', bulk:true, moq:5, variants:[{name:'Ink Color',values:['Black','Blue','Red']}], specs:['50 pieces per box','Fine ballpoint writing','School and office pack','Budget bulk option'], description:'Reliable classroom ballpen pack for exams, forms, and everyday writing.', reviews },
  { id:'dong-a-my-gel', name:'Dong-A My Gel Pen 0.5mm 12s', brand:'Dong-A', category:'Writing Supplies', price:219, compareAt:260, rating:4.8, sold:760, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/4053_129.jpg', badge:'16% OFF', availability:'In Stock', variants:[{name:'Ink Color',values:['Black','Blue','Assorted']}], specs:['0.5mm gel ink','12 pens per pack','Smooth writing','Student note-taking'], description:'Popular gel pen pack for clean and colorful school notes.', reviews },
  { id:'stabilo-boss-4', name:'STABILO BOSS Original Highlighter 4-Color Set', brand:'STABILO', category:'Writing Supplies', price:235, compareAt:285, rating:4.9, sold:930, image:'https://down-ph.img.susercontent.com/file/c989fc403c402fb2685d629e3ca4377a', badge:'18% OFF', availability:'In Stock', variants:[{name:'Set',values:['4 colors','6 colors','8 colors']}], specs:['Chisel tip','Anti-dry-out design','Fluorescent colors','Study highlighting'], description:'Highlighter set for reviewers, teachers, and students preparing notes.', reviews },
  { id:'correction-tape-tombow', name:'Tombow Mono Correction Tape 5mm x 6m', brand:'Tombow', category:'Writing Supplies', price:85, compareAt:99, rating:4.8, sold:2100, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/5446_4793.jpg', badge:'14% OFF', availability:'In Stock', variants:[{name:'Pack',values:['Single','3 pcs','6 pcs']}], specs:['5mm tape width','6m tape length','Dry correction','No drying time'], description:'Clean correction tape for notebooks, worksheets, and office documents.', reviews },
  { id:'cattleya-notebook-80', name:'Cattleya Composition Notebook 80 Leaves', brand:'Cattleya', category:'Notebooks & Pads', price:42, compareAt:50, rating:4.7, sold:5000, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/7991_6654.JPG', badge:'16% OFF', availability:'In Stock', variants:[{name:'Type',values:['Writing','Math','Science']}], specs:['80 leaves','Composition size','Ruled pages','Student notebook'], description:'Affordable notebook for daily subject notes and assignments.', reviews },
  { id:'vecos-notebook-pack', name:'Veco Spiral Notebook 80 Leaves 5-Pack', brand:'Veco', category:'Notebooks & Pads', price:225, compareAt:275, rating:4.6, sold:730, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/8332_6848.jpg', badge:'18% OFF', availability:'In Stock', variants:[{name:'Rule',values:['Wide ruled','College ruled']}], specs:['5 notebooks','80 leaves each','Spiral binding','Assorted covers'], description:'Budget notebook pack for multiple subjects and back-to-school lists.', reviews },
  { id:'best-buy-intermediate-pad', name:'Best Buy Intermediate Pad Paper 80 Leaves', brand:'Best Buy', category:'Paper Products', price:38, compareAt:45, rating:4.6, sold:3800, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/8059_6690.jpg', badge:'16% OFF', availability:'In Stock', specs:['Intermediate pad','80 leaves','Ruled paper','School writing pad'], description:'Everyday pad paper for quizzes, assignments, and classroom work.', reviews },
  { id:'corona-bond-paper-a4', name:'Corona A4 Bond Paper 70gsm Ream', brand:'Corona', category:'Paper Products', price:245, compareAt:285, rating:4.8, sold:1900, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/8966_7016.jpg', badge:'14% OFF', availability:'Check bulk availability', bulk:true, moq:5, variants:[{name:'Size',values:['A4','Short','Long']}], specs:['500 sheets per ream','70gsm','Multi-purpose copy paper','For printing and worksheets'], description:'Reliable bond paper for teachers, school offices, modules, and projects.', reviews },
  { id:'hard-copy-bond-paper-short', name:'Hard Copy Short Bond Paper 70gsm Ream', brand:'Hard Copy', category:'Paper Products', price:235, compareAt:270, rating:4.7, sold:1100, image:'https://down-ph.img.susercontent.com/file/ph-11134207-81ztn-mhr92i69cgledc', badge:'13% OFF', availability:'Check bulk availability', bulk:true, moq:5, specs:['Short size','500 sheets','70gsm','Printer and copier compatible'], description:'School and office paper ream for forms, exams, and handouts.', reviews },
  { id:'sterling-index-card', name:'Sterling Index Card 3x5 Ruled 100s', brand:'Sterling', category:'Paper Products', price:68, compareAt:80, rating:4.6, sold:1400, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/8084_6703.JPG', badge:'15% OFF', availability:'In Stock', variants:[{name:'Size',values:['3x5','4x6','5x8']}], specs:['100 cards','Ruled index card','Review and flashcard use','White'], description:'Index cards for reviewers, vocabulary drills, reports, and presentations.', reviews },
  { id:'oslo-paper-pack', name:'Oslo Paper 20-Sheet Project Pack', brand:'Best Buy', category:'Paper Products', price:45, compareAt:55, rating:4.6, sold:1800, image:'https://img.lazcdn.com/g/p/edb8d2e714ccb146efac8fc96c7eaa1f.jpg_720x720q80.jpg', badge:'18% OFF', availability:'In Stock', specs:['20 sheets','White Oslo paper','Project and art use','School-ready pack'], description:'Thick project paper for drawings, reports, and school submissions.', reviews },
  { id:'cartolina-assorted', name:'Assorted Cartolina 10-Sheet Pack', brand:'Best Buy', category:'Art Supplies', price:120, compareAt:145, rating:4.5, sold:870, image:'https://down-ph.img.susercontent.com/file/ph-11134207-81zti-mid3omwmlh4xb4', badge:'17% OFF', availability:'In Stock', variants:[{name:'Color',values:['Assorted','White','Black']}], specs:['10 sheets','Assorted colors','Poster and project use','Large format'], description:'Cartolina pack for classroom projects, posters, and visual aids.', reviews },
  { id:'faber-castell-color-24', name:'Faber-Castell Classic Colour Pencils 24 Colors', brand:'Faber-Castell', category:'Art Supplies', price:285, compareAt:345, rating:4.9, sold:1250, image:'https://down-ph.img.susercontent.com/file/sg-11134202-7rdxu-mcfoskt7ysm3d3', badge:'17% OFF', availability:'In Stock', variants:[{name:'Set',values:['12 colors','24 colors','36 colors']}], specs:['24 colors','Break-resistant leads','Hexagonal pencils','School art set'], description:'Trusted coloring pencil set for art classes and school projects.', reviews },
  { id:'crayola-crayons-24', name:'Crayola Crayons 24 Colors', brand:'Crayola', category:'Art Supplies', price:139, compareAt:165, rating:4.8, sold:2400, image:'https://down-ph.img.susercontent.com/file/sg-11134275-824h4-me810447kt8j5f', badge:'16% OFF', availability:'In Stock', variants:[{name:'Set',values:['8 colors','16 colors','24 colors','48 colors']}], specs:['24 crayon colors','Non-toxic','Classic school art supply','Smooth coloring'], description:'Popular crayon set for preschool, grade school, and art activities.', reviews },
  { id:'prang-watercolor-8', name:'Prang Watercolor Set 8 Colors', brand:'Prang', category:'Art Supplies', price:199, compareAt:235, rating:4.7, sold:540, image:'https://down-ph.img.susercontent.com/file/ph-11134207-7rasm-m4cs1v5ya7ll1c', badge:'15% OFF', availability:'In Stock', specs:['8 watercolor cakes','Brush included','Washable colors','For school art projects'], description:'Compact watercolor set for art class and creative school projects.', reviews },
  { id:'elmer-glue-130g', name:"Elmer's School Glue 130g", brand:"Elmer's", category:'Adhesives & Tapes', price:95, compareAt:110, rating:4.8, sold:1550, image:'https://down-ph.img.susercontent.com/file/ph-11134207-7qul3-libcxmx0pmccae', badge:'14% OFF', availability:'In Stock', variants:[{name:'Size',values:['40g','130g','225g']}], specs:['White school glue','130g bottle','Washable','For paper and crafts'], description:'Classic school glue for projects, art activities, and classroom use.', reviews },
  { id:'scotch-tape-3m', name:'3M Scotch Transparent Tape 18mm x 25m', brand:'3M', category:'Adhesives & Tapes', price:79, compareAt:95, rating:4.8, sold:1100, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/8983_1380.jpg', badge:'17% OFF', availability:'In Stock', variants:[{name:'Pack',values:['Single','3 pcs','6 pcs']}], specs:['18mm x 25m','Transparent tape','General school and office use','Fits standard dispensers'], description:'Clear tape for wrapping, school projects, labels, and office tasks.', reviews },
  { id:'masking-tape', name:'Masking Tape 24mm Project Roll', brand:'Deli', category:'Adhesives & Tapes', price:55, compareAt:65, rating:4.5, sold:680, image:'https://down-ph.img.susercontent.com/file/sg-11134201-7ra1j-mb9b9lidxe1vae', badge:'15% OFF', availability:'In Stock', specs:['24mm width','Paper masking tape','Easy tear','Project and labeling use'], description:'Useful masking tape for classroom activities, labels, and crafts.', reviews },
  { id:'deli-stapler', name:'Deli Stapler with Staples Set', brand:'Deli', category:'Office & Teacher Supplies', price:149, compareAt:180, rating:4.7, sold:760, image:'https://img.drz.lazcdn.com/static/bd/p/40f3e55a33075e24407f9747116d306c.jpg_720x720q80.jpg', badge:'17% OFF', availability:'In Stock', variants:[{name:'Color',values:['Blue','Black','White']}], specs:['Desktop stapler','Staples included','For No. 10/standard staples','Teacher desk essential'], description:'Reliable stapler for worksheets, handouts, reports, and office documents.', reviews },
  { id:'delI-staples-10', name:'Deli No.10 Staples 10-Box Pack', brand:'Deli', category:'Office & Teacher Supplies', price:115, compareAt:135, rating:4.6, sold:620, image:'https://down-ph.img.susercontent.com/file/sg-11134201-7rd6f-lufy3idme09795', badge:'15% OFF', availability:'Check bulk availability', bulk:true, moq:10, specs:['10 small boxes','No.10 staple size','For mini staplers','Classroom/office supply'], description:'Bulk staple pack for faculty rooms, offices, and classroom stations.', reviews },
  { id:'post-it-notes', name:'3M Post-it Notes 3x3 Yellow Pad 100 Sheets', brand:'3M', category:'Office & Teacher Supplies', price:99, compareAt:120, rating:4.8, sold:980, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/images/2032.jpg', badge:'18% OFF', availability:'In Stock', variants:[{name:'Color',values:['Yellow','Pastel','Neon']}], specs:['3x3 inches','100 sheets','Repositionable adhesive','Notes and reminders'], description:'Sticky notes for study reminders, teacher planning, and office labels.', reviews },
  { id:'whiteboard-marker-pilot', name:'Pilot Whiteboard Marker 3-Color Set', brand:'Pilot', category:'Office & Teacher Supplies', price:185, compareAt:220, rating:4.8, sold:890, image:'https://down-ph.img.susercontent.com/file/th-11134207-7qul2-lfj3c3oc8alq17', badge:'16% OFF', availability:'In Stock', variants:[{name:'Set',values:['3 colors','6 markers','12 markers']}], specs:['Dry-erase ink','Black/blue/red set','Bullet tip','For whiteboards'], description:'Teacher-friendly marker set for classrooms, review centers, and offices.', reviews },
  { id:'whiteboard-eraser', name:'Magnetic Whiteboard Eraser', brand:'Deli', category:'Office & Teacher Supplies', price:89, compareAt:105, rating:4.6, sold:490, image:'https://down-ph.img.susercontent.com/file/ph-11134207-7rasd-m7t63ymlw2958e', badge:'15% OFF', availability:'In Stock', specs:['Magnetic back','Soft felt surface','For whiteboards','Compact classroom size'], description:'Simple classroom eraser for whiteboards and teaching spaces.', reviews },
  { id:'clearbook-20', name:'Clear Book Folder A4 20 Pockets', brand:'Deli', category:'Bags & Storage', price:129, compareAt:155, rating:4.7, sold:1350, image:'https://down-ph.img.susercontent.com/file/ph-11134211-7rasl-m7gervm3zl2j5c', badge:'17% OFF', availability:'In Stock', variants:[{name:'Color',values:['Blue','Black','Clear','Pink']}], specs:['A4 size','20 pockets','Plastic cover','For reports and handouts'], description:'Clearbook for organizing worksheets, certificates, reports, and reviewers.', reviews },
  { id:'expanding-envelope', name:'Expanding Envelope A4 13 Pockets', brand:'Deli', category:'Bags & Storage', price:189, compareAt:225, rating:4.7, sold:780, image:'https://down-ph.img.susercontent.com/file/sg-11134201-7qvep-lg1v6q0v8ysl9c', badge:'16% OFF', availability:'In Stock', variants:[{name:'Color',values:['Blue','Black','Pink','Green']}], specs:['13 pockets','A4 document size','Button closure','Subject/file organizer'], description:'Organizer envelope for separating subjects, modules, forms, and receipts.', reviews },
  { id:'plastic-envelope-button', name:'Plastic Envelope with Button A4 10-Pack', brand:'Best Buy', category:'Bags & Storage', price:210, compareAt:250, rating:4.6, sold:690, image:'https://down-ph.img.susercontent.com/file/ph-11134201-7r992-lx9eltw6m0rl0c', badge:'16% OFF', availability:'Check bulk availability', bulk:true, moq:5, variants:[{name:'Color',values:['Clear','Blue','Assorted']}], specs:['10 envelopes','A4 size','Button closure','Water-resistant plastic'], description:'Bulk document envelopes for students, teachers, and school offices.', reviews },
  { id:'school-backpack', name:'Water-Resistant Student Backpack 18L', brand:'Deli', category:'Bags & Storage', price:499, compareAt:599, rating:4.5, sold:340, image:'https://down-ph.img.susercontent.com/file/sg-11134201-7rdya-lzabeez6688c21', badge:'17% OFF', availability:'In Stock', variants:[{name:'Color',values:['Black','Navy','Gray']}], specs:['18L capacity','Water-resistant fabric','Front utility pocket','Padded straps'], description:'Budget student backpack for books, notebooks, and daily school essentials.', reviews },
  { id:'casio-fx-991es', name:'Casio FX-991ES Plus Scientific Calculator', brand:'Casio', category:'Calculators & Tech', price:1099, compareAt:1299, rating:4.9, sold:420, image:'https://down-ph.img.susercontent.com/file/sg-11134201-7rdwh-lyyjisky503bfb', badge:'15% OFF', availability:'In Stock', specs:['Natural textbook display','417 functions','Solar + battery','For high school/college math'], description:'Popular scientific calculator for algebra, trigonometry, statistics, and exams.', reviews },
  { id:'casio-fx-82ms', name:'Casio FX-82MS Scientific Calculator', brand:'Casio', category:'Calculators & Tech', price:549, compareAt:650, rating:4.8, sold:580, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/6893_6311.jpg', badge:'16% OFF', availability:'In Stock', specs:['2-line display','240 functions','Hard slide case','High school calculator'], description:'Reliable calculator for general science and math subjects.', reviews },
  { id:'sharp-el531', name:'Sharp EL-W531 Scientific Calculator', brand:'Sharp', category:'Calculators & Tech', price:699, compareAt:820, rating:4.7, sold:260, image:'https://down-ph.img.susercontent.com/file/ph-11134207-7r98r-m0azrosjduys61', badge:'15% OFF', availability:'In Stock', specs:['Scientific functions','Multi-line display','Protective cover','School and college use'], description:'Scientific calculator option for students needing math and science support.', reviews },
  { id:'usb-flash-kingston-32', name:'Kingston DataTraveler 32GB USB Flash Drive', brand:'Kingston', category:'Calculators & Tech', price:249, compareAt:299, rating:4.8, sold:950, image:'https://down-ph.img.susercontent.com/file/0db185f4b8382bf04a261870213c7d95', badge:'17% OFF', availability:'In Stock', variants:[{name:'Capacity',values:['32GB','64GB','128GB']}], specs:['32GB storage','USB-A interface','Portable files','For projects and presentations'], description:'Handy USB drive for school files, reports, slides, and printing shops.', reviews },
  { id:'maped-scissors', name:'Maped Essentials School Scissors 13cm', brand:'Maped', category:'Art Supplies', price:85, compareAt:99, rating:4.7, sold:860, image:'https://down-ph.img.susercontent.com/file/79e73422937f394b5953af99eb23704c', badge:'14% OFF', availability:'In Stock', variants:[{name:'Color',values:['Blue','Pink','Green']}], specs:['13cm scissors','Rounded tip','Student-safe design','For paper crafts'], description:'Student scissors for art projects, cutting activities, and classroom use.', reviews },
  { id:'deli-cutter', name:'Deli Utility Cutter with Safety Lock', brand:'Deli', category:'Office & Teacher Supplies', price:69, compareAt:85, rating:4.5, sold:540, image:'https://down-ph.img.susercontent.com/file/ph-11134207-7qukx-lff4tm3cyzhb20', badge:'19% OFF', availability:'In Stock', specs:['Retractable cutter','Safety lock','Replaceable blade','For office/project use'], description:'Utility cutter for teachers and office staff handling paper and packaging.', reviews },
  { id:'ruler-12-inch', name:'12-Inch Plastic Ruler 10-Piece Pack', brand:'Best Buy', category:'Writing Supplies', price:95, compareAt:120, rating:4.6, sold:1150, image:'https://down-ph.img.susercontent.com/file/bbe3cb47d38b4073d8554eea40dfda9b', badge:'21% OFF', availability:'Check bulk availability', bulk:true, moq:10, variants:[{name:'Color',values:['Clear','Assorted']}], specs:['12-inch ruler','10 pieces','Metric and inch marks','Classroom pack'], description:'Affordable ruler pack for classrooms, art projects, and school kits.', reviews },
  { id:'eraser-faber-12', name:'Faber-Castell Dust-Free Eraser 12-Pack', brand:'Faber-Castell', category:'Writing Supplies', price:185, compareAt:220, rating:4.8, sold:840, image:'https://down-ph.img.susercontent.com/file/my-11134207-7r98p-llkda0d7xenh36', badge:'16% OFF', availability:'In Stock', specs:['12 erasers','Dust-free formula','Clean erasing','For graphite pencils'], description:'Clean eraser pack for students, classrooms, and school supply kits.', reviews },
  { id:'sharpener-faber-12', name:'Faber-Castell Sharpener 12-Piece Classroom Pack', brand:'Faber-Castell', category:'Writing Supplies', price:199, compareAt:240, rating:4.7, sold:610, image:'https://down-id.img.susercontent.com/file/id-11134207-7r98y-ltg449mvywhuf9', badge:'17% OFF', availability:'Check bulk availability', bulk:true, moq:5, specs:['12 sharpeners','Single-hole design','Compact plastic body','Classroom supply pack'], description:'Practical sharpener pack for school kits, classrooms, and art stations.', reviews },
  { id:'paper-clips-deli', name:'Deli Paper Clips 100-Piece Box', brand:'Deli', category:'Office & Teacher Supplies', price:45, compareAt:55, rating:4.5, sold:720, image:'https://down-ph.img.susercontent.com/file/ph-11134207-7rasg-m8pmbetxs5um0e', badge:'18% OFF', availability:'In Stock', specs:['100 clips','Metal paper clips','For documents and worksheets','Office basic'], description:'Basic paper clips for teachers, admin staff, and study organization.', reviews },
  { id:'binder-clips-12', name:'Binder Clips Assorted 12-Piece Pack', brand:'Deli', category:'Office & Teacher Supplies', price:89, compareAt:105, rating:4.6, sold:840, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/8929_7005.png', badge:'15% OFF', availability:'In Stock', variants:[{name:'Size',values:['Small','Medium','Large','Assorted']}], specs:['12 clips','Assorted sizes','Strong metal grip','For papers and modules'], description:'Binder clips for modules, reports, lesson plans, and office files.', reviews },
  { id:'manila-paper-10', name:'Manila Paper 10-Sheet Classroom Pack', brand:'Best Buy', category:'Paper Products', price:85, compareAt:100, rating:4.5, sold:1300, image:'https://down-ph.img.susercontent.com/file/ph-11134207-7rasi-m2iya9tdsdc25b', badge:'15% OFF', availability:'In Stock', specs:['10 sheets','Large paper format','For reports and group work','Classroom project staple'], description:'Manila paper pack for group presentations, visual aids, and classroom reports.', reviews },
  { id:'folder-long-10', name:'Long Folder Assorted 10-Piece Pack', brand:'Best Buy', category:'Paper Products', price:110, compareAt:135, rating:4.6, sold:1050, image:'https://down-ph.img.susercontent.com/file/ph-11134207-81zte-mh1j84ns7myy20', badge:'19% OFF', availability:'Check bulk availability', bulk:true, moq:10, variants:[{name:'Color',values:['Assorted','White','Blue']}], specs:['10 folders','Long size','Assorted colors','For school documents'], description:'Folder pack for reports, requirements, and school office filing.', reviews },
  { id:'grade-school-kit', name:'Grade School Starter Kit', brand:'Prime Academics', category:'School Kits', price:399, compareAt:499, rating:4.8, sold:640, image:'https://down-ph.img.susercontent.com/file/ph-11134207-7rasg-m961k65tqzoz4f', badge:'20% OFF', availability:'Check bulk availability', bulk:true, moq:5, specs:['Curated school kit','For grade school students','Budget-friendly bundle','Ready for back-to-school'], kitItems:['2 notebooks','Mongol pencils','Eraser','Ruler','Crayola crayons'], description:'Back-to-school starter kit with daily essentials for grade school students.', reviews },
  { id:'high-school-writing-kit', name:'High School Writing Kit', brand:'Prime Academics', category:'School Kits', price:299, compareAt:380, rating:4.7, sold:590, image:'https://down-ph.img.susercontent.com/file/ph-11134207-7r98t-lz0hy581n3i239', badge:'21% OFF', availability:'Check bulk availability', bulk:true, moq:5, specs:['Writing-focused bundle','For junior/senior high','Includes pads and pens','Good for daily subjects'], kitItems:['Intermediate pad','Ballpens','Correction tape','Index cards'], description:'Affordable writing bundle for quizzes, notes, assignments, and reviewers.', reviews },
  { id:'art-project-kit', name:'Art Project Kit', brand:'Prime Academics', category:'School Kits', price:499, compareAt:620, rating:4.8, sold:410, image:'https://down-ph.img.susercontent.com/file/ph-11134208-7rasc-m71zeosklrbp3d', badge:'20% OFF', availability:'Check bulk availability', bulk:true, moq:5, specs:['Art and project bundle','For school projects','Includes color and paper supplies','Ready-to-use kit'], kitItems:['Colored pencils','Glue','Scissors','Cartolina','Oslo paper'], description:'Project-ready art kit for assignments, posters, and creative school work.', reviews },
  { id:'teacher-classroom-kit', name:'Teacher Classroom Kit', brand:'Prime Academics', category:'School Kits', price:899, compareAt:1099, rating:4.9, sold:180, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/8966_7016.jpg', badge:'18% OFF', availability:'Check bulk availability', bulk:true, moq:3, specs:['Teacher supply bundle','Classroom-ready','For lessons and admin work','Bulk quote available'], kitItems:['Whiteboard markers','Bond paper','Sticky notes','Folders','Binder clips'], description:'Practical teacher kit for daily classroom teaching and paperwork.', reviews },
  { id:'exam-week-kit', name:'Exam Week Essentials Kit', brand:'Prime Academics', category:'School Kits', price:249, compareAt:315, rating:4.7, sold:520, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/3633_210.jpg', badge:'21% OFF', availability:'In Stock', specs:['Exam supply bundle','For students','Compact and affordable','Reviewer-friendly'], kitItems:['Pencils','Black pens','Eraser','Sharpener','Index cards'], description:'Small exam prep kit with must-have writing and review supplies.', reviews },
  { id:'paper-filing-kit', name:'Paper & Filing Kit for Reports', brand:'Prime Academics', category:'School Kits', price:349, compareAt:430, rating:4.6, sold:320, image:'https://down-ph.img.susercontent.com/file/ph-11134207-7rasg-m19ofj12piwp25', badge:'19% OFF', availability:'Check bulk availability', bulk:true, moq:5, specs:['Report filing bundle','For students and teachers','Document organization kit','Bulk order ready'], kitItems:['Folders','Plastic envelope','Paper clips','Index cards','Bond paper sampler'], description:'Easy report and document kit for school requirements and submissions.', reviews },
  { id:'teacher-marker-bulk', name:'Teacher Whiteboard Marker Classroom Pack 12s', brand:'Pilot', category:'Deals', price:520, compareAt:650, rating:4.8, sold:230, image:'https://down-ph.img.susercontent.com/file/sg-11134202-8226l-mhok5mlr46bn70', badge:'20% OFF', availability:'Check bulk availability', bulk:true, moq:3, variants:[{name:'Color',values:['Black','Blue','Assorted']}], specs:['12 markers','Dry-erase ink','Classroom bulk pack','For faculty rooms'], description:'Bulk marker pack for teachers, tutorial centers, and school offices.', reviews },
  { id:'notebook-classroom-pack', name:'Composition Notebook Classroom Pack 20s', brand:'Cattleya', category:'Deals', price:790, compareAt:960, rating:4.7, sold:260, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/7991_6654.JPG', badge:'18% OFF', availability:'Check bulk availability', bulk:true, moq:3, specs:['20 notebooks','80 leaves each','Assorted covers','Classroom/bulk pack'], description:'Notebook classroom pack for advisories, school drives, and bulk resupply.', reviews },
  { id:'pen-pencil-combo', name:'Pen & Pencil Budget Combo Pack', brand:'Prime Academics', category:'Deals', price:199, compareAt:260, rating:4.7, sold:780, image:'https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/3633_210.jpg', badge:'23% OFF', availability:'In Stock', specs:['Mixed writing supplies','Budget student bundle','Pens + pencils + eraser','Back-to-school ready'], kitItems:['3 ballpens','6 pencils','2 erasers','1 sharpener'], description:'Affordable combo for students who need basic writing supplies quickly.', reviews },
];

export const featuredProducts = products.slice(0, 12);
export const flashDeals = products.filter((p) => p.compareAt).slice(0, 10);
export const schoolKits = products.filter((p) => p.category === 'School Kits');
export const under99 = products.filter((p) => p.price < 100);
export const bulkPacks = products.filter((p) => p.bulk);

export function getProduct(id: string) {
  return products.find((product) => product.id === id);
}

export function formatCardPrice(price: number) {
  return `₱${Math.round(price).toLocaleString('en-PH')}`;
}

export function formatMoney(price: number) {
  return `₱${price.toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}
